name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex

      - name: Compile LaTeX file
        run: |
          pdflatex main.tex

      - name: Create docs directory and move PDF
        run: |
          mkdir -p docs
          mv main.pdf docs/

      - name: Commit and push changes
        run: |
          git config --global user.email "Shadi.Zumor@hs-ruhrwest.de"
          git config --global user.name "Shzuhrw"
          git add docs/main.pdf
          git commit -m "Add generated PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
