name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex

      - name: Compile LaTeX file
        run: |
          pdflatex main.tex
          
      - name: Move PDF to docs directory
        run: |
          mkdir -p docs
          mv main.pdf docs/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: docs/main.pdf
